version: '3'
services:

  frontend:
    build: ./front
    container_name: front
    depends_on:
      - backend
    ports:
      - 80:8080

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"

  rabbitmq:
      build: ./rabbitmq
      container_name: rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
        - "61614:61614"
